# Generated by Django 5.2.7 on 2025-12-19 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtoken',
            name='studio',
        ),
        migrations.AddField(
            model_name='gmailtoken',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gmail_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
