# Generated by Django 5.2.7 on 2025-12-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0002_remove_gmailtoken_studio_gmailtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='smtp_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
