# Generated by Django 5.2.7 on 2026-01-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0003_email_smtp_message_id'),
        ('projects', '0019_alter_phase_created_at_alter_phase_updated_at_and_more'),
        ('users', '0012_remove_studio_gmail_user_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projects', models.ManyToManyField(related_name='email_threads', to='projects.project')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='users.studio')),
            ],
        ),
    ]
