# Generated by Django 5.2.7 on 2026-02-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0004_emailthread'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
