# Generated by Django 5.2.7 on 2026-03-20 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0007_gmailtoken_history_id'),
        ('users', '0013_user_pay_per_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=255)),
                ('summary', models.TextField()),
                ('email_count', models.IntegerField(default=0)),
                ('last_email_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='email',
            name='gmail_email_thread_id_idx',
        ),
        migrations.RenameIndex(
            model_name='email',
            new_name='gmail_email_studio__1c22f6_idx',
            old_name='gmail_email_studio_received_idx',
        ),
        migrations.RenameIndex(
            model_name='email',
            new_name='gmail_email_studio__2cc05a_idx',
            old_name='gmail_email_studio_thread_idx',
        ),
        migrations.RenameIndex(
            model_name='email',
            new_name='gmail_email_studio__b5925f_idx',
            old_name='gmail_email_studio_thread_recv_idx',
        ),
        migrations.AlterField(
            model_name='email',
            name='thread_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='threadsummary',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_summaries', to='users.studio'),
        ),
        migrations.AlterUniqueTogether(
            name='threadsummary',
            unique_together={('thread_id', 'studio')},
        ),
    ]
