# Generated by Django 5.2.7 on 2026-04-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0008_threadsummary_remove_email_gmail_email_thread_id_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadsummary',
            name='suggested_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
