# Generated by Django 5.2.7 on 2026-03-25 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('change_type', models.CharField(choices=[('feature', 'Feature'), ('fix', 'Bug Fix'), ('improvement', 'Improvement'), ('breaking', 'Breaking Change'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(help_text='Date the change was released or effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change Log',
                'verbose_name_plural': 'Change Logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
