# Generated by Django 5.2.7 on 2026-06-08 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0030_public_profile_and_portfolio'),
        ('users', '0033_studio_stripe_connect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='supplier_logos/')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified suppliers appear in the global catalog browse experience.')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Supplier Account',
                'verbose_name_plural': 'Supplier Accounts',
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=999, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('trade_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('dimension', models.CharField(blank=True, max_length=999, null=True)),
                ('materials', models.CharField(blank=True, max_length=999, null=True)),
                ('weight', models.CharField(blank=True, max_length=999, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_products_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to='supplier_portal.supplieraccount')),
            ],
            options={
                'verbose_name': 'Catalog Product',
                'verbose_name_plural': 'Catalog Products',
            },
        ),
        migrations.CreateModel(
            name='CatalogProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog_product_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='supplier_portal.catalogproduct')),
            ],
            options={
                'verbose_name': 'Catalog Product Image',
                'verbose_name_plural': 'Catalog Product Images',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('status', models.CharField(choices=[('RQ', 'Requested'), ('CF', 'Confirmed'), ('SH', 'Shipped'), ('DL', 'Delivered'), ('CN', 'Cancelled')], default='RQ', max_length=2)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_city', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_country', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='supplier_portal.catalogproduct')),
                ('procurement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_order_line', to='projects.procurement')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studio')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='supplier_portal.supplieraccount')),
            ],
            options={
                'verbose_name': 'Supplier Order Line',
                'verbose_name_plural': 'Supplier Order Lines',
            },
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['is_published', 'category'], name='supplier_po_is_publ_fd66a1_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogproduct',
            index=models.Index(fields=['supplier', 'is_published'], name='supplier_po_supplie_1b93be_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorderline',
            index=models.Index(fields=['supplier', 'status'], name='supplier_po_supplie_409cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierorderline',
            index=models.Index(fields=['supplier', 'created_at'], name='supplier_po_supplie_2b1685_idx'),
        ),
    ]
