# Generated by Django 5.2.7 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieraccount',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='stripe_connect_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='stripe_connect_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplieraccount',
            name='stripe_connect_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('paid', 'Paid'),
                    ('failed', 'Failed'),
                    ('refunded', 'Refunded'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
