# Generated by Django 5.2.7 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_portal', '0002_supplier_stripe_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorderline',
            name='quote_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='quote_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='quote_status',
            field=models.CharField(
                choices=[
                    ('NR', 'Not requested'),
                    ('RQ', 'Quote requested'),
                    ('QT', 'Quoted'),
                    ('DC', 'Declined'),
                ],
                default='NR',
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='quoted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='quoted_lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
