# Generated by Django 5.2.7 on 2026-06-06 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0003_designasset_3d'),
        ('library', '0010_alter_product_box_dimension_and_more'),
        ('projects', '0030_public_profile_and_portfolio'),
        ('users', '0032_alter_rolepermission_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Presentation', max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='presentation_thumbnails/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_dashboard_published', models.BooleanField(default=False)),
                ('web_published', models.BooleanField(default=False)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('show_product_pricing', models.BooleanField(default=False)),
                ('show_supplier_info', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='projects.project')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='users.studio')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='presentation_slides/%Y/%m/')),
                ('canvas_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='presentations.presentation')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PresentationPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_type', models.CharField(choices=[('product', 'Product'), ('scene', 'Scene')], max_length=20)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('show_pricing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='design.designasset')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.product')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='presentations.presentationslide')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PresentationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('text', models.TextField()),
                ('author_type', models.CharField(choices=[('studio', 'Studio User'), ('client', 'Client')], default='studio', max_length=20)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation_comments', to=settings.AUTH_USER_MODEL)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='presentations.presentationslide')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
