# Generated by Django 5.2.7 on 2025-11-25 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0001_initial'),
        ('library', '0001_initial'),
        ('users', '0002_remove_user_studios_user_studio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('pre_loaded_tasks', models.JSONField(blank=True, default={}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('RS', 'Residential'), ('CM', 'Commercial'), ('HS', 'Hospitaliy')], default='RS', max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=200, null=True)),
                ('os_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_windows', models.CharField(blank=True, max_length=200, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('project_code', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=200, null=True)),
                ('total_budget', models.FloatField(blank=True, null=True)),
                ('vt_rate', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_schedule', models.CharField(blank=True, choices=[('FF', '50/50 Split'), ('TP', 'Three Payments'), ('PF', 'Per Phase'), ('M', 'Monthly')], max_length=200, null=True)),
                ('assignees', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_projects', to='crm.client')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_projects', to='crm.client')),
                ('phases', models.ManyToManyField(blank=True, null=True, to='projects.phase')),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studio')),
                ('rooms', models.ManyToManyField(blank=True, null=True, to='projects.room')),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(blank=True, choices=[('REQ', 'Requested'), ('REC', 'Received'), ('SUB', 'Submitted')], max_length=200, null=True)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('DFT', 'Draft'), ('HDN', 'Hidden'), ('SL', 'Selected'), ('QT', 'Quoting'), ('IR', 'Internal Review'), ('CR', 'Client Review'), ('RSMT', 'Resubmit'), ('CL', 'Closed'), ('REJ', 'Rejected'), ('APR', 'Approved'), ('ORD', 'Ordered'), ('PD', 'Payment Due'), ('IP', 'In Production'), ('IT', 'In Transit'), ('INS', 'Installed'), ('DEL', 'Delivered')], max_length=200, null=True)),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.purchaseorder')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library.product')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.room')),
            ],
        ),
    ]
