# Generated by Django 5.2.7 on 2025-11-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
