# Generated by Django 5.2.7 on 2025-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_phase_end_date_phase_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('ARC', 'Archive'), ('COM', 'Complete')], default='AC', max_length=200, null=True),
        ),
    ]
