# Generated by Django 5.2.7 on 2025-11-25 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='pre_loaded_tasks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='assignees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='phases',
            field=models.ManyToManyField(blank=True, to='projects.phase'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='projects.room'),
        ),
    ]
