# Generated by Django 5.2.7 on 2025-11-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_phase_created_at_phase_created_by_phase_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='client_approval',
            field=models.CharField(blank=True, choices=[('APR', 'Approved'), ('REJ', 'Rejected'), ('RVW', 'Review')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='inv_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='inv_received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='inv_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='po_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='po_received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='po_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='status',
            field=models.CharField(blank=True, choices=[('QT', 'Quoting'), ('IR', 'Internal Review'), ('OS', 'Out of Stock'), ('CR', 'Client Review'), ('ORD', 'Ordered'), ('PD', 'Payment Due'), ('IT', 'In Transit'), ('INS', 'Installed'), ('DEL', 'Delivered')], default='IR', max_length=200, null=True),
        ),
    ]
