# Generated by Django 5.2.7 on 2025-11-29 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_invoice_created_at_invoice_created_by_and_more'),
        ('projects', '0006_procurement_client_approval_procurement_inv_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.invoice'),
        ),
    ]
