# Generated by Django 5.2.7 on 2025-11-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_procurement_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('EA', 'ea'), ('M', 'm'), ('M^^2', 'm^^2'), ('ST', 'set')], max_length=200, null=True),
        ),
    ]
