# Generated by Django 5.2.7 on 2025-11-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_procurement_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_banner',
            field=models.ImageField(blank=True, null=True, upload_to='project_banners/'),
        ),
    ]
