# Generated by Django 5.2.7 on 2025-12-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_phase_created_by_alter_phase_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ffne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='status',
            field=models.CharField(blank=True, choices=[('QT', 'Quoting'), ('IR', 'Internal Review'), ('IA', 'Internally Approved'), ('OS', 'Out of Stock'), ('CR', 'Client Review'), ('ORD', 'Ordered'), ('PD', 'Payment Due'), ('IT', 'In Transit'), ('INS', 'Installed'), ('DEL', 'Delivered')], default='IR', max_length=200, null=True),
        ),
    ]
