# Generated by Django 5.2.7 on 2025-12-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_ffne_alter_procurement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logictics_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
