# Generated by Django 5.2.7 on 2025-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comments_options_remove_comments_comment_and_more'),
        ('projects', '0012_project_logictics_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comment.comments'),
        ),
    ]
