# Generated by Django 5.2.7 on 2025-12-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_procurement_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='ETA',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurement',
            name='logistic_status',
            field=models.CharField(blank=True, choices=[('IT', 'In Transit'), ('DD', 'Delivered')], max_length=200, null=True),
        ),
    ]
