# Generated by Django 5.2.7 on 2025-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_procurement_eta_procurement_logistic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='logistic_status',
            field=models.CharField(blank=True, choices=[('IT', 'In Transit'), ('DD', 'Delivered')], default='IT', max_length=200, null=True),
        ),
    ]
