# Generated by Django 5.2.7 on 2025-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_procurement_logistic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='client_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
