# Generated by Django 5.2.7 on 2025-12-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_procurement_client_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='procurement_client_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
