# Generated by Django 5.2.7 on 2025-12-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_procurement_client_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('EA', 'ea'), ('M', 'm'), ('M^^2', 'm^^2'), ('ST', 'set')], default='EA', max_length=200, null=True),
        ),
    ]
