# Generated by Django 5.2.7 on 2026-01-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_phase_created_at_alter_phase_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='hour_budget',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='total_budget',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
