# Generated by Django 5.2.7 on 2026-02-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_phase_hour_budget_phase_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='contractor_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
