# Generated by Django 5.2.7 on 2026-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead'),
        ('projects', '0021_procurement_contractor_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secondary_client',
            field=models.ManyToManyField(blank=True, help_text='Additional clients who have access to this project in the client portal.', related_name='secondary_projects', to='crm.client'),
        ),
    ]
