# Generated by Django 5.2.7 on 2026-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_secondary_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='logistic_status',
            field=models.CharField(blank=True, choices=[('NO', 'Not Ordered'), ('IT', 'In Transit'), ('DD', 'Delivered')], default='NO', max_length=200, null=True),
        ),
    ]
