# Generated by Django 5.2.7 on 2026-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_add_project_fk_to_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
