# Generated by Django 5.2.7 on 2026-04-03 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_procurement_internally_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('ARC', 'Archive'), ('COM', 'Complete'), ('WON', 'Won')], default='AC', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ProjectProposalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_tokens', to='projects.project')),
            ],
        ),
    ]
