# Generated by Django 5.2.7 on 2026-04-08 05:34

from django.db import migrations, models


def copy_address_fields(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        updated = False
        if project.delivery_address and not project.delivery_address_line_1:
            project.delivery_address_line_1 = project.delivery_address
            updated = True
        if project.billing_address and not project.billing_address_line_1:
            project.billing_address_line_1 = project.billing_address
            updated = True
        if project.logictics_address and not project.logistics_address_line_1:
            project.logistics_address_line_1 = project.logictics_address
            updated = True
        if updated:
            project.save(update_fields=[
                'delivery_address_line_1',
                'billing_address_line_1',
                'logistics_address_line_1',
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_project_project_status_projectproposaltoken'),
    ]

    operations = [
        # Add new fields first
        migrations.AddField(
            model_name='project',
            name='delivery_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics_address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics_address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='logistics_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Copy existing single-field values into the new _line_1 fields
        migrations.RunPython(copy_address_fields, migrations.RunPython.noop),
        # Now safe to drop the old fields
        migrations.RemoveField(
            model_name='project',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='logictics_address',
        ),
    ]
