# Generated by Django 5.2.7 on 2026-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_project_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hide_client_on_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='portfolio_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
