# Generated by Django 5.2.7 on 2026-06-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_public_profile_and_portfolio'),
        ('supplier_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='catalog_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='supplier_portal.catalogproduct'),
        ),
    ]
