"use client"

import type React from "react"
import { useEffect, useRef, useState } from "react"

import Image from "next/image"
import Link from "next/link"
import { useTranslations } from "next-intl"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { CtaButton } from "@/components/cta-button"
import { cn } from "@/lib/utils"
import { PortugueseTilesBg } from "@/components/graphics/portuguese-tiles-bg"
import { ClipboardList, FileText, Stamp, Truck, Receipt, Link2, Sparkles } from "lucide-react"
import { BreadcrumbSchema, usePlatformBreadcrumbs } from "@/components/seo/breadcrumb-schema"

const container = "mx-auto max-w-[1200px] px-6 sm:px-8"
const H1 = "text-[30px] sm:text-5xl md:text-[56px] font-medium tracking-tight leading-[1.1]"
const H2 = "text-2xl sm:text-[30px] md:text-4xl font-medium tracking-tight"
const Lead = "text-base sm:text-lg text-stone-600"

const CLAY = "#E07A57"

const KPI_KEYS = ["onTimeDeliveries", "posAutoGenerated", "approvedSelections", "vendorsTracked"] as const
const KPI_ACCENTS = ["#6E7A58", "#C78A3B", CLAY, "#4B5960"] as const

const FEATURE_TILES = [
  {
    key: "specSheets",
    icon: FileText,
    accent: "#E68E71",
    placeholderQuery: "specification%20sheets%20ui%20clean",
  },
  {
    key: "approvals",
    icon: Stamp,
    accent: "#6E7A58",
    placeholderQuery: "client%20approvals%20ui%20modal",
  },
  {
    key: "purchaseOrders",
    icon: ClipboardList,
    accent: "#C78A3B",
    placeholderQuery: "purchase%20orders%20table%20ui",
  },
  {
    key: "vendorsDeliveries",
    icon: Truck,
    accent: "#4B5960",
    placeholderQuery: "vendor%20delivery%20tracking%20board",
  },
  {
    key: "receipts",
    icon: Receipt,
    accent: "#B75A41",
    placeholderQuery: "receipts%20table%20ui",
  },
  {
    key: "linkToBudget",
    icon: Link2,
    accent: "#8FA58F",
    placeholderQuery: "budget%20linking%20finance%20ui",
  },
] as const

const APPROVAL_ITEMS = [
  {
    key: "brassLamp",
    imgSrc: "/images/procurement/hero/side-lamp-new.png",
    status: "approved" as const,
  },
  {
    key: "boucleChair",
    imgSrc: "/images/procurement/hero/side-lounge.png",
    status: "rejected" as const,
  },
] as const

const LIBRARY_ITEMS = [
  { key: "chandelier", img: "/images/library/orbital-brass-chandelier.png" },
  { key: "canvasArt", img: "/images/library/abstract-canvas-art.png" },
  { key: "accentChair", img: "/images/library/mid-century-accent-chair.png" },
] as const

const RELATED_LINKS = [
  { key: "projects", href: "/platform/projects", icon: ClipboardList },
  { key: "finance", href: "/platform/finance", icon: Receipt },
  { key: "clientPortal", href: "/platform/client-portal", icon: Stamp },
  { key: "pricing", href: "/pricing", icon: Sparkles },
] as const

const SPEC_KEYS = ["material", "finish", "dimensions", "leadTime"] as const

const DEMO_DOMAIN = "myluxinterior.com"

function Kpi({ label, value, accent }: { label: string; value: string; accent: string }) {
  return (
    <div
      className="rounded-2xl bg-white px-5 py-4 text-center shadow-[0_6px_22px_rgba(0,0,0,0.06)] ring-1"
      style={{ ringColor: "rgba(0,0,0,0.06)" as React.CSSProperties["color"] }}
    >
      <div className="text-xs font-semibold tracking-wide" style={{ color: "#7D786C" }}>
        {label}
      </div>
      <div className="mt-1 text-2xl font-semibold text-stone-900">{value}</div>
      <div className="mx-auto mt-3 h-1.5 w-10 rounded-full" style={{ backgroundColor: accent }} />
    </div>
  )
}

function ApprovedChip({ label }: { label: string }) {
  return (
    <span
      className="inline-flex items-center rounded-full bg-white px-3 py-1 text-xs font-medium shadow-sm ring-1"
      style={{ color: "#4E6243", ringColor: "rgba(78,98,67,0.28)" as React.CSSProperties["color"] }}
    >
      {label}
    </span>
  )
}

function StatusPill({ status, approvedLabel, rejectedLabel }: { status: "approved" | "rejected"; approvedLabel: string; rejectedLabel: string }) {
  const isApproved = status === "approved"
  const styles = isApproved
    ? {
        backgroundColor: "rgba(110,122,88,0.16)",
        color: "#4E6243",
        boxShadow: "inset 0 0 0 1px rgba(110,122,88,0.28)",
      }
    : {
        backgroundColor: "rgba(224,122,87,0.12)",
        color: "#B75A41",
        boxShadow: "inset 0 0 0 1px rgba(224,122,87,0.28)",
      }
  return (
    <span
      className="inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold shadow-sm"
      style={styles as React.CSSProperties}
    >
      {isApproved ? approvedLabel : rejectedLabel}
    </span>
  )
}

function ApprovalsList() {
  const t = useTranslations("platformProcurement")
  const approvedLabel = t("status.approved")
  const rejectedLabel = t("status.rejected")

  return (
    <div className="p-2 sm:p-3">
      <ul className="divide-y divide-stone-200">
        {APPROVAL_ITEMS.map((item) => {
          const title = t(`clientApprovals.items.${item.key}.title`)
          const room = t(`clientApprovals.items.${item.key}.room`)
          const vendor = t(`clientApprovals.items.${item.key}.vendor`)
          const code = t(`clientApprovals.items.${item.key}.code`)
          return (
            <li key={item.key} className="flex items-center gap-4 p-3 sm:p-4">
              <div className="relative h-20 w-20 sm:h-24 sm:w-24 overflow-hidden rounded-xl bg-stone-100 ring-1 ring-stone-200">
                <Image
                  src={item.imgSrc || "/placeholder.svg?height=192&width=192&query=product%20thumbnail"}
                  alt={t("clientApprovals.thumbnailAlt", { title, vendor, room })}
                  fill
                  sizes="(max-width: 640px) 80px, 96px"
                  className="object-contain p-1.5"
                />
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <div className="min-w-0">
                    <div className="truncate text-sm font-semibold text-stone-900">{title}</div>
                    <div className="text-xs text-stone-600">
                      {room} • {vendor}
                    </div>
                  </div>
                  <StatusPill status={item.status} approvedLabel={approvedLabel} rejectedLabel={rejectedLabel} />
                </div>
                <div className="mt-1 text-xs text-stone-700">{code}</div>
              </div>
            </li>
          )
        })}
      </ul>
    </div>
  )
}

const TILE_BORDER = "rounded-3xl overflow-hidden border border-stone-200 bg-white shadow-lg"

function HeroTile({
  heightClass,
  src,
  alt,
  sizes,
  object = "object-cover",
  objectPosition,
  showApproved = false,
  approvedLabel,
}: {
  heightClass: string
  src: string
  alt: string
  sizes: string
  object?: "object-cover" | "object-contain"
  objectPosition?: string
  showApproved?: boolean
  approvedLabel?: string
}) {
  const inset = "inset-0"
  const rounded = "rounded-[inherit]"
  return (
    <div className={TILE_BORDER}>
      <div className={`relative w-full ${heightClass}`}>
        <div className={`absolute ${inset} overflow-hidden ${rounded}`}>
          <Image
            src={src || "/placeholder.svg"}
            alt={alt}
            fill
            sizes={sizes}
            className={`${object} rounded-[inherit]`}
            style={objectPosition ? { objectPosition, borderRadius: "inherit" } : { borderRadius: "inherit" }}
            priority={false}
          />
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 rounded-[inherit] ring-1 ring-stone-200"
            style={{ boxShadow: "inset 0 0 0 10px #ffffff" }}
          />
          {showApproved && approvedLabel ? (
            <div className="pointer-events-none absolute bottom-2 left-1/2 z-[1] -translate-x-1/2 sm:bottom-3">
              <ApprovedChip label={approvedLabel} />
            </div>
          ) : null}
        </div>
      </div>
    </div>
  )
}

function FeatureTile({
  title,
  desc,
  icon: Icon,
  imgAlt,
  accent = "#EFEAE2",
  placeholderQuery,
}: {
  title: string
  desc: string
  icon?: React.ComponentType<React.SVGProps<SVGSVGElement>>
  imgAlt: string
  accent?: string
  placeholderQuery: string
}) {
  return (
    <Card className="group overflow-hidden border-stone-200 bg-white shadow-sm ring-1 ring-black/0 transition hover:-translate-y-0.5 hover:shadow-md hover:ring-black/5">
      <CardContent className="p-0">
        <div className="h-1.5 w-full" style={{ backgroundColor: accent }} aria-hidden />
        <div className="relative h-40 w-full sm:h-44 md:h-48">
          <Image
            src={`/placeholder.svg?height=320&width=640&query=${encodeURIComponent(placeholderQuery)}`}
            alt={imgAlt}
            fill
            sizes="(max-width: 768px) 100vw, (max-width: 1280px) 33vw, 400px"
            className="object-cover"
          />
        </div>
        <div className="p-4">
          <div className="flex items-center gap-2">
            {Icon ? (
              <span
                className="inline-flex h-8 w-8 items-center justify-center rounded-lg ring-1"
                style={{
                  backgroundColor: "rgba(224,122,87,0.12)",
                  color: CLAY,
                  boxShadow: "inset 0 0 0 1px rgba(224,122,87,0.28)",
                }}
              >
                <Icon className="h-4 w-4" aria-hidden="true" />
              </span>
            ) : null}
            <h3 className="text-base font-semibold leading-tight text-stone-900">{title}</h3>
          </div>
          <p className="mt-2 text-sm text-stone-700">{desc}</p>
        </div>
      </CardContent>
    </Card>
  )
}

function AiImportDemo() {
  const t = useTranslations("platformProcurement.aiImport")
  const FULL_URL = t("demoUrl")

  type Phase = "idle" | "typing" | "loading" | "done"
  const [phase, setPhase] = useState<Phase>("idle")
  const [typed, setTyped] = useState("")
  const [pressAnim, setPressAnim] = useState(false)
  const [progress, setProgress] = useState(0)

  const rootRef = useRef<HTMLDivElement | null>(null)
  const started = useRef(false)

  useEffect(() => {
    const el = rootRef.current
    if (!el) return
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting && !started.current) {
            started.current = true
            setPhase("typing")
          }
        })
      },
      { threshold: 0.35 },
    )
    io.observe(el)
    return () => io.disconnect()
  }, [])

  useEffect(() => {
    if (phase !== "typing") return
    setTyped("")
    let i = 0
    const speed = 28
    const id = setInterval(() => {
      i++
      setTyped(FULL_URL.slice(0, i))
      if (i >= FULL_URL.length) {
        clearInterval(id)
        setTimeout(() => {
          setPressAnim(true)
          setPhase("loading")
          setTimeout(() => setPressAnim(false), 260)
        }, 320)
      }
    }, speed)
    return () => clearInterval(id)
  }, [phase, FULL_URL])

  useEffect(() => {
    if (phase !== "loading") return
    setProgress(0)
    const id = setInterval(() => {
      setProgress((p) => {
        const next = p + Math.random() * 18
        if (next >= 100) {
          clearInterval(id)
          setTimeout(() => setPhase("done"), 350)
          return 100
        }
        return next
      })
    }, 220)
    return () => clearInterval(id)
  }, [phase])

  const showSkeleton = phase === "loading"
  const showResult = phase === "done"

  const buttonLabel =
    phase === "loading" ? t("buttons.working") : phase === "done" ? t("buttons.imported") : t("buttons.addWithAi")

  return (
    <div ref={rootRef} className="mx-auto mt-8 max-w-4xl" aria-live="polite" aria-label={t("demoAria")}>
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center">
        <div className="flex grow items-center gap-2 rounded-lg border border-stone-300 bg-white px-3 py-3">
          <span
            className="inline-flex h-8 w-8 items-center justify-center rounded-lg ring-1"
            style={{
              backgroundColor: "rgba(224,122,87,0.12)",
              color: CLAY,
              boxShadow: "inset 0 0 0 1px rgba(224,122,87,0.28)",
            }}
            aria-hidden="true"
            title={t("aiTitle")}
          >
            <Sparkles className="h-4 w-4" />
          </span>
          <label htmlFor="ai-url-input" className="sr-only">
            {t("productUrlLabel")}
          </label>
          <input
            id="ai-url-input"
            type="url"
            value={phase === "idle" ? "" : typed}
            readOnly
            className="w-full bg-transparent text-sm text-stone-700 outline-none"
            aria-label={t("productUrlLabel")}
            placeholder={t("urlPlaceholder")}
          />
        </div>

        <CtaButton
          label={buttonLabel}
          variant={phase === "loading" || phase === "done" ? "white" : "slate"}
          className={
            phase === "loading" || phase === "done"
              ? "!bg-[#E07A57] !text-white !ring-[#E07A57] hover:!bg-[#CE6B4E] transition-colors " +
                (pressAnim ? "scale-95 transition-transform" : "")
              : ""
          }
        />
      </div>

      <div className="mt-6 overflow-hidden rounded-2xl border border-stone-200 bg-white shadow-lg">
        {showSkeleton ? (
          <div className="relative">
            <div className="absolute left-0 top-0 h-1 bg-stone-200" style={{ width: "100%" }} />
            <div
              className="absolute left-0 top-0 h-1"
              style={{
                width: `${progress}%`,
                background: "linear-gradient(90deg, rgba(224,122,87,0.3) 0%, rgba(224,122,87,0.9) 100%)",
                transition: "width 220ms ease",
              }}
              aria-hidden
            />
          </div>
        ) : null}

        {showSkeleton ? (
          <div className="grid gap-0 sm:grid-cols-2" aria-label={t("loadingAria")}>
            <div className="h-[28rem] animate-pulse bg-stone-100 sm:h-[30rem] md:h-[32rem]" />
            <div className="p-5 sm:p-6">
              <div className="h-5 w-40 animate-pulse rounded bg-stone-100" />
              <div className="mt-2 h-5 w-28 animate-pulse rounded bg-stone-100" />
              <div className="mt-3 h-4 w-64 animate-pulse rounded bg-stone-100" />
              <div className="mt-4 space-y-2">
                <div className="h-4 w-[90%] animate-pulse rounded bg-stone-100" />
                <div className="h-4 w-[80%] animate-pulse rounded bg-stone-100" />
                <div className="h-4 w-[70%] animate-pulse rounded bg-stone-100" />
              </div>
              <div className="mt-6 flex justify-center gap-3">
                <div className="h-10 w-40 animate-pulse rounded bg-stone-100" />
                <div className="h-10 w-32 animate-pulse rounded bg-stone-100" />
              </div>
            </div>
          </div>
        ) : null}

        {showResult ? (
          <div className="grid items-stretch gap-0 sm:grid-cols-2">
            <div className="relative h-[28rem] w-full bg-white sm:h-[30rem] md:h-[32rem]">
              <Image
                src="/images/procurement/ai-import-chair.png"
                alt={t("product.imageAlt")}
                fill
                sizes="(max-width: 768px) 100vw, 50vw"
                className="object-contain opacity-0 transition-opacity duration-700 [animation:fadeIn_0.7s_ease_forwards]"
                priority={false}
              />
            </div>

            <div className="p-5 sm:p-6">
              <div className="flex items-center gap-2">
                <span className="inline-flex h-8 items-center rounded-full border border-stone-200 bg-white px-2.5 text-xs text-stone-700">
                  {t("badge")}
                </span>
                <span className="text-xs text-stone-500">{t("sourceLabel", { domain: DEMO_DOMAIN })}</span>
              </div>

              <h3 className="mt-3 text-2xl font-semibold tracking-tight text-stone-900">{t("product.title")}</h3>
              <p className={cn("mt-2", Lead)}>{t("product.description")}</p>
              <div className="mt-2 text-lg font-semibold text-stone-900">{t("product.price")}</div>
              <div className="mt-1 text-sm text-stone-600">{t("product.vendor")}</div>

              <dl className="mt-5 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2">
                {SPEC_KEYS.map((key) => (
                  <div key={key} className="rounded-lg border border-stone-200 bg-stone-50 p-3">
                    <dt className="text-stone-600">{t(`specLabels.${key}`)}</dt>
                    <dd className="font-medium text-stone-900">{t(`specValues.${key}`)}</dd>
                  </div>
                ))}
              </dl>

              <div className="mt-6 flex flex-wrap justify-center gap-3">
                <CtaButton
                  label={t("addToLibrary")}
                  variant="white"
                  className="!bg-[#E07A57] !text-white !ring-[#E07A57] hover:!bg-[#CE6B4E]"
                />
                <CtaButton label={t("createPo")} variant="white" />
              </div>
            </div>
          </div>
        ) : null}
      </div>

      <style>{`
@keyframes fadeIn {
to { opacity: 1 }
}
`}</style>
    </div>
  )
}

function LibraryCards() {
  const t = useTranslations("platformProcurement.library")

  return (
    <div className="mt-8 overflow-x-auto">
      <div className="flex snap-x snap-mandatory gap-4">
        {LIBRARY_ITEMS.map((item) => {
          const title = t(`items.${item.key}.title`)
          const brand = t(`items.${item.key}.brand`)
          const price = t(`items.${item.key}.price`)
          const tag = t(`items.${item.key}.tag`)
          return (
            <Card
              key={item.key}
              className="snap-start shrink-0 basis-[82%] overflow-hidden border-stone-200 shadow-md sm:basis-[55%] md:basis-[42%] lg:basis-[32%]"
            >
              <CardContent className="p-0">
                <div className="relative h-[300px] w-full sm:h-[340px]">
                  <Image
                    src={item.img || "/placeholder.svg"}
                    alt={t("cardImageAlt", { title, brand, tag })}
                    fill
                    sizes="(max-width: 768px) 82vw, (max-width: 1280px) 42vw, 32vw"
                    className="object-cover"
                    priority={false}
                  />
                </div>
                <div className="p-5">
                  <div className="min-w-0">
                    <div className="truncate text-base font-semibold text-stone-900 sm:text-lg">{title}</div>
                    <div className="mt-0.5 text-[11px] font-medium tracking-wider text-stone-500">{brand}</div>
                  </div>
                  <div className="mt-4 flex items-center justify-between">
                    <div className="text-lg font-semibold text-stone-900 sm:text-xl">{price}</div>
                    <span
                      className="inline-flex items-center rounded-full px-3 py-1 text-xs"
                      style={{
                        backgroundColor: "rgba(214,177,150,0.16)",
                        boxShadow: "inset 0 0 0 1px rgba(214,177,150,0.38)",
                        color: "#4E4943",
                      }}
                    >
                      {tag}
                    </span>
                  </div>
                </div>
              </CardContent>
            </Card>
          )
        })}
      </div>
    </div>
  )
}

export function ProcurementPageContent() {
  const t = useTranslations("platformProcurement")
  const ts = useTranslations("platformShared")
  const breadcrumbs = usePlatformBreadcrumbs("procurement")
  const approvedLabel = t("status.approved")

  return (
    <>
      <BreadcrumbSchema items={breadcrumbs} />
      <main className="bg-white">
        <section className="relative isolate overflow-hidden pb-10 pt-12 sm:pb-12 sm:pt-16 md:pt-20">
          <PortugueseTilesBg height="min(520px, 56vh)" opacity={0.16} fadeStop={0.5} />
          <div className="mx-auto max-w-none px-6 sm:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <Badge variant="outline" className="rounded-full border-stone-300 bg-stone-50 text-stone-700">
                {t("hero.badge")}
              </Badge>
              <h1 className={cn("mt-4 text-center", H1)}>{t("hero.title")}</h1>
              <p className={cn("mt-4 text-center", Lead)}>{t("hero.subtitle")}</p>
            </div>

            <div className="mx-auto mt-10 w-full max-w-[min(1680px,96vw)]">
              <div className="grid items-end gap-4 sm:grid-cols-12 sm:gap-4 lg:gap-6">
                <div className="col-span-1 sm:col-span-4 md:col-span-3">
                  <HeroTile
                    heightClass="h-[270px] sm:h-[340px] md:h-[450px] lg:h-[495px]"
                    src="/images/procurement/hero/side-lounge.png"
                    alt={t("hero.images.loungeAlt")}
                    sizes="(max-width: 768px) 100vw, (max-width: 1400px) 30vw, 32vw"
                    object="object-contain"
                    showApproved
                    approvedLabel={approvedLabel}
                  />
                </div>
                <div className="col-span-2 sm:col-span-12 md:col-span-6">
                  <HeroTile
                    heightClass="h-[360px] sm:h-[450px] md:h-[600px] lg:h-[660px]"
                    src="/images/procurement/hero/center-room.png"
                    alt={t("hero.images.centerAlt")}
                    sizes="(max-width: 768px) 100vw, (max-width: 1400px) 40vw, 36vw"
                    object="object-cover"
                  />
                </div>
                <div className="col-span-1 sm:col-span-4 md:col-span-3">
                  <HeroTile
                    heightClass="h-[270px] sm:h-[340px] md:h-[450px] lg:h-[495px]"
                    src="/images/procurement/hero/side-lamp-new.png"
                    alt={t("hero.images.lampAlt")}
                    sizes="(max-width: 768px) 100vw, (max-width: 1400px) 30vw, 32vw"
                    object="object-contain"
                    showApproved
                    approvedLabel={approvedLabel}
                  />
                </div>
              </div>
            </div>

            <div className="mx-auto mt-12 max-w-4xl sm:mt-14">
              <div className="mx-auto grid grid-cols-2 gap-4 sm:grid-cols-4">
                {KPI_KEYS.map((key, i) => (
                  <Kpi
                    key={key}
                    label={t(`kpis.${key}.label`)}
                    value={t(`kpis.${key}.value`)}
                    accent={KPI_ACCENTS[i]}
                  />
                ))}
              </div>
            </div>
          </div>
        </section>

        <section id="ai" className="bg-white py-14 sm:py-20" aria-labelledby="ai-procurement">
          <div className={container}>
            <div className="mx-auto max-w-3xl text-center">
              <h2 id="ai-procurement" className={H2}>
                {t("aiImport.sectionTitle")}
              </h2>
              <p className={cn("mt-3", Lead)}>{t("aiImport.sectionSubtitle")}</p>
            </div>
            <AiImportDemo />
          </div>
        </section>

        <section className="bg-white py-14 sm:py-20" aria-labelledby="procurement-features">
          <div className={container}>
            <h2 id="procurement-features" className="sr-only">
              {t("features.sectionAria")}
            </h2>
            <div className="grid gap-4 md:grid-cols-3">
              {FEATURE_TILES.map((tile) => (
                <FeatureTile
                  key={tile.key}
                  title={t(`features.${tile.key}.title`)}
                  desc={t(`features.${tile.key}.desc`)}
                  icon={tile.icon}
                  imgAlt={t(`features.${tile.key}.imgAlt`)}
                  accent={tile.accent}
                  placeholderQuery={tile.placeholderQuery}
                />
              ))}
            </div>
          </div>
        </section>

        <section className="bg-white py-14 sm:py-20" aria-labelledby="client-approvals">
          <div className={container}>
            <div className="grid items-center gap-8 lg:grid-cols-2 lg:gap-12">
              <div>
                <h2
                  id="client-approvals"
                  className="text-2xl sm:text-[30px] md:text-4xl font-medium tracking-tight text-stone-900"
                >
                  {t("clientApprovals.title")}
                </h2>
                <p className={cn("mt-4", Lead)}>{t("clientApprovals.subtitle")}</p>
              </div>
              <ApprovalsList />
            </div>
          </div>
        </section>

        <section className="bg-white py-14 sm:py-20" aria-labelledby="library-cards">
          <div className={container}>
            <h2 id="library-cards" className="sr-only">
              {t("library.sectionAria")}
            </h2>
            <LibraryCards />
          </div>
        </section>

        <section className="bg-stone-50 py-16 sm:py-20">
          <div className={container}>
            <div className="mx-auto max-w-4xl">
              <h2 className="text-2xl sm:text-[30px] md:text-4xl font-medium tracking-tight text-center text-stone-900">
                {t("relatedLinks.title")}
              </h2>
              <p className="mt-3 text-center text-stone-600">{t("relatedLinks.subtitle")}</p>
              <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                {RELATED_LINKS.map((link) => {
                  const Icon = link.icon
                  return (
                    <Link
                      key={link.key}
                      href={link.href}
                      className="group rounded-xl border border-stone-200 bg-white p-5 transition-all hover:border-stone-300 hover:shadow-md"
                    >
                      <Icon className="h-6 w-6 text-stone-600 group-hover:text-stone-900" />
                      <h3 className="mt-3 font-semibold text-stone-900">{t(`relatedLinks.${link.key}.title`)}</h3>
                      <p className="mt-1 text-sm text-stone-600">{t(`relatedLinks.${link.key}.desc`)}</p>
                    </Link>
                  )
                })}
              </div>
            </div>
          </div>
        </section>

        <section className="relative isolate overflow-hidden py-24" style={{ backgroundColor: "#F1BBAA" }}>
          <div
            aria-hidden
            className="pointer-events-none absolute inset-0 opacity-[0.06]"
            style={{ backgroundImage: "url('/textures/grain.png')", backgroundSize: "200px 200px" }}
          />
          <div className={container}>
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-2xl sm:text-[28px] md:text-[32px] font-medium tracking-tight text-stone-950">
                {t("finalCta.title")}
              </h2>
              <p className="mt-3 text-lg text-stone-900/80">{t("finalCta.subtitle")}</p>
              <div className="mt-8 flex justify-center">
                <CtaButton href="/signup" variant="slate" label={ts("startForFree")} showArrow arrowVariant="white" />
              </div>
              <p className="mt-3 text-xs sm:text-sm text-stone-900/60">{ts("noCreditCardRequired")}</p>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}
