# Generated by Django 5.2.7 on 2025-11-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_studios_user_studio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studios',
            field=models.ManyToManyField(related_name='users', through='users.UserStudio', to='users.studio'),
        ),
    ]
