# Generated by Django 5.2.7 on 2025-11-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_studios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='studios',
        ),
    ]
