# Generated by Django 5.2.7 on 2025-11-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_invitation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStudio',
        ),
    ]
