# Generated by Django 5.2.7 on 2025-11-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_userstudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='default_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='default_tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
