# Generated by Django 5.2.7 on 2025-12-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='gmail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='xero',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
