# Generated by Django 5.2.7 on 2025-12-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_studio_gmail_studio_xero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='gmail',
        ),
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
