# Generated by Django 5.2.7 on 2026-01-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_studio_gmail_user_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_per_hour',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
