# Generated by Django 5.2.7 on 2026-03-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hours_per_week',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
