# Generated by Django 5.2.7 on 2026-04-08 05:34

from django.db import migrations


def copy_address_to_address_line_1(apps, schema_editor):
    Studio = apps.get_model('users', 'Studio')
    for studio in Studio.objects.exclude(address__isnull=True).exclude(address=''):
        if not studio.address_line_1:
            studio.address_line_1 = studio.address
            studio.save(update_fields=['address_line_1'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_project_template'),
    ]

    operations = [
        # Copy address → address_line_1 before dropping the old field
        migrations.RunPython(copy_address_to_address_line_1, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='studio',
            old_name='town_city',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='address',
        ),
    ]
