# Generated by Django 5.2.7 on 2026-04-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('projects.view', 'Projects • view'), ('projects.edit', 'Projects • edit'), ('projects.delete', 'Projects • delete'), ('tasks.view', 'Tasks • view'), ('tasks.edit', 'Tasks • edit'), ('tasks.delete', 'Tasks • delete'), ('finance.view', 'Finance • view'), ('finance.edit', 'Finance • edit'), ('finance.delete', 'Finance • delete'), ('clients.view', 'Clients • view'), ('clients.edit', 'Clients • edit'), ('clients.delete', 'Clients • delete'), ('library.view', 'Library • view'), ('library.edit', 'Library • edit'), ('library.delete', 'Library • delete'), ('procurement.view', 'Procurement • view'), ('procurement.edit', 'Procurement • edit'), ('procurement.delete', 'Procurement • delete'), ('documents.view', 'Documents • view'), ('documents.edit', 'Documents • edit'), ('documents.delete', 'Documents • delete'), ('reports.view', 'Reports • view'), ('team.view', 'Team • view'), ('team.edit', 'Team • edit'), ('team.delete', 'Team • delete'), ('settings.edit', 'Settings • edit')], max_length=50),
        ),
    ]
