# Generated by Django 5.2.7 on 2026-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='notion',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
