# Generated by Django 5.2.7 on 2026-05-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_userappearancepreferences_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappearancepreferences',
            name='theme',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark'), ('midnight', 'Midnight Basalt'), ('forest', 'Earthy Forest'), ('terracotta', 'Warm Terracotta'), ('cobalt', 'Cobalt Blue'), ('quartz', 'Rose Quartz'), ('pink', 'Modern Pink')], default='system', max_length=20),
        ),
    ]
