# Generated by Django 5.2.7 on 2025-12-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_invitation_sender_alter_user_studio'),
        ('xero', '0003_xerotoken_created_at_xerotoken_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='xerotoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_tokens_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='xerotoken',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studio'),
        ),
        migrations.AlterField(
            model_name='xerotoken',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_tokens_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
