"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Sparkles, FileText, Loader2 } from "lucide-react"
import { toast } from "@/hooks/use-toast"
import { postData } from "@/lib/Api"
import type { ProposalData } from "../proposal-drawer"

interface ScopeStepProps {
  data: ProposalData
  onUpdate: (updates: Partial<ProposalData>) => void
}

const scopeTemplates = [
  {
    id: "residential",
    name: "Residential Interior",
    content: `## Project Scope

### Design Development
- Initial consultation and space assessment
- Concept development and mood boards
- Space planning and layout optimization
- Material and finish selection
- Custom furniture design and specification

### Documentation
- Detailed drawings and specifications
- 3D visualizations and renderings
- Material schedules and procurement lists
- Installation coordination

### Project Management
- Contractor coordination and oversight
- Quality control and site visits
- Timeline management and progress reporting
- Final styling and installation supervision`,
  },
  {
    id: "commercial",
    name: "Commercial Space",
    content: `## Project Scope

### Strategic Planning
- Brand alignment and space strategy
- Workflow optimization analysis
- Compliance and accessibility review
- Sustainability considerations

### Design Services
- Concept development and presentations
- Space planning and furniture layouts
- Material selection and specification
- Lighting and technology integration

### Implementation
- Construction documentation
- Vendor coordination and procurement
- Installation management
- Post-occupancy evaluation`,
  },
  {
    id: "hospitality",
    name: "Hospitality Design",
    content: `## Project Scope

### Concept Development
- Brand experience design
- Guest journey mapping
- Operational flow optimization
- Ambiance and atmosphere creation

### Design Execution
- Public area design and layout
- Guest room prototyping
- F&B space design
- Wayfinding and signage systems

### Project Delivery
- FF&E specification and procurement
- Art and accessory curation
- Installation coordination
- Staff training and handover`,
  },
]

function buildAiPayload(data: ProposalData) {
  return {
    project_type: data.title || "",
    client_name: data.client || "",
    project_description: data.scope || "",
    budget_range: data.message || "",
    timeline: data.validUntil || "",
    rooms: "",
    style_preference: data.branding || "",
  }
}

export function ScopeStep({ data, onUpdate }: ScopeStepProps) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [activeTab, setActiveTab] = useState("write")

  const handleAIGenerate = async () => {
    setIsGenerating(true)
    try {
      const payload = buildAiPayload(data)
      const result = await postData({ url: "/crm/proposals/ai-draft/", data: payload })

      if (result?.scope) {
        onUpdate({ scope: result.scope })
        setActiveTab("write")
        toast({ description: "Scope generated by AI ✨", duration: 2500 })
      } else {
        toast({ description: "AI returned no scope content", variant: "destructive", duration: 3000 })
      }
    } catch (error: any) {
      const msg =
        error?.response?.data
          ? JSON.stringify(error.response.data)
          : error?.message || "AI generation failed"
      toast({ description: msg, variant: "destructive", duration: 3000 })
    } finally {
      setIsGenerating(false)
    }
  }

  const handleTemplateSelect = (template: (typeof scopeTemplates)[0]) => {
    onUpdate({ scope: template.content })
    setActiveTab("write")
  }

  return (
    <div className="space-y-6">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
        <TabsList className="grid w-full grid-cols-3 bg-stone-100">
          <TabsTrigger value="write" className="data-[state=active]:bg-white">
            Write Custom
          </TabsTrigger>
          <TabsTrigger value="templates" className="data-[state=active]:bg-white">
            Use Template
          </TabsTrigger>
          <TabsTrigger value="ai" className="data-[state=active]:bg-white">
            AI Generate
          </TabsTrigger>
        </TabsList>

        <TabsContent value="write" className="space-y-4 mt-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label className="text-sm font-semibold text-gray-900">
                Scope Description <span className="text-red-500">*</span>
              </Label>
              <Button
                variant="outline"
                size="sm"
                onClick={handleAIGenerate}
                disabled={isGenerating}
                className="gap-2 h-8 text-xs"
              >
                {isGenerating ? (
                  <Loader2 className="w-3 h-3 animate-spin" />
                ) : (
                  <Sparkles className="w-3 h-3 text-amber-500" />
                )}
                {isGenerating ? "Generating…" : "AI Enhance"}
              </Button>
            </div>
            <Textarea
              placeholder="Describe the project scope, deliverables, and what's included..."
              value={data.scope || ""}
              onChange={(e) => onUpdate({ scope: e.target.value })}
              rows={12}
              className="bg-white resize-none text-sm border-gray-200"
            />
            <p className="text-xs text-gray-500">
              Use Markdown formatting for better presentation. This will be formatted in the final proposal.
            </p>
          </div>
        </TabsContent>

        <TabsContent value="templates" className="space-y-3 mt-4">
          {scopeTemplates.map((template) => (
            <div
              key={template.id}
              className="flex items-start justify-between p-4 border border-gray-200 rounded-lg hover:border-gray-300 transition-colors"
            >
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <FileText className="w-4 h-4 text-gray-400" />
                  <h4 className="text-sm font-medium text-gray-900">{template.name}</h4>
                </div>
                <p className="text-sm text-gray-500 line-clamp-2">
                  {template.content
                    .split("\n")
                    .find((line) => line.includes("###"))
                    ?.replace("### ", "") || "Professional template for this project type"}
                </p>
              </div>
              <Button
                variant="outline"
                size="sm"
                onClick={() => handleTemplateSelect(template)}
                className="shrink-0 h-8 text-xs"
              >
                Use Template
              </Button>
            </div>
          ))}
        </TabsContent>

        <TabsContent value="ai" className="mt-4">
          <div className="text-center py-8 space-y-4">
            <p className="text-sm text-gray-500">
              Generate a comprehensive project scope based on your client and project details.
            </p>
            <Button
              onClick={handleAIGenerate}
              disabled={isGenerating}
              className="gap-2 bg-gray-900 hover:bg-gray-800 text-white"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating scope…
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Draft with AI
                </>
              )}
            </Button>
          </div>
        </TabsContent>
      </Tabs>

      {/* Terms & Conditions */}
      <div className="space-y-3 pt-4 border-t border-gray-200">
        <div className="flex items-center justify-between">
          <Label className="text-sm font-semibold text-gray-900">Terms & Conditions</Label>
          <div className="flex gap-2">
            <button
              type="button"
              className="text-xs text-gray-500 hover:text-gray-700 px-2 py-1 rounded border border-gray-200 hover:bg-stone-50"
              onClick={() => onUpdate({ terms: `TERMS & CONDITIONS\n\n1. SCOPE OF WORK\nThe Designer agrees to provide interior design services as outlined in the project scope.\n\n2. PAYMENT TERMS\nPayment is due according to the schedule outlined in this proposal. Late payments may incur a 1.5% monthly service charge.\n\n3. CHANGES & REVISIONS\nMinor revisions are included. Major changes may require additional fees and timeline adjustments.\n\n4. TIMELINE\nProject timeline is estimated and subject to client approvals, product availability, and contractor schedules.\n\n5. CANCELLATION\nEither party may terminate with 30 days written notice. Client is responsible for work completed to date.\n\n6. LIABILITY\nDesigner's liability is limited to the total contract value.\n\n7. GOVERNING LAW\nThis agreement is governed by the laws of England and Wales.` })}
            >
              Residential
            </button>
            <button
              type="button"
              className="text-xs text-gray-500 hover:text-gray-700 px-2 py-1 rounded border border-gray-200 hover:bg-stone-50"
              onClick={() => onUpdate({ terms: `COMMERCIAL TERMS & CONDITIONS\n\n1. PROJECT SCOPE\nServices include space planning, design development, and project coordination as specified.\n\n2. PAYMENT SCHEDULE\nInvoices are due within 30 days. Projects may be suspended for overdue payments exceeding 45 days.\n\n3. APPROVALS & PERMITS\nClient is responsible for obtaining necessary permits and approvals.\n\n4. COMPLIANCE\nAll designs will comply with applicable building codes and accessibility requirements.\n\n5. INTELLECTUAL PROPERTY\nDesign concepts remain property of Designer until final payment is received.\n\n6. FORCE MAJEURE\nNeither party is liable for delays due to circumstances beyond reasonable control.\n\n7. GOVERNING LAW\nThis agreement is governed by the laws of England and Wales.` })}
            >
              Commercial
            </button>
          </div>
        </div>
        <Textarea
          placeholder="Enter terms & conditions or use a template above..."
          value={data.terms || ""}
          onChange={(e) => onUpdate({ terms: e.target.value })}
          className="bg-white border-gray-200 min-h-[120px] text-sm resize-none"
          rows={5}
        />
      </div>
    </div>
  )
}
