# Generated by Django 5.2.7 on 2025-12-16 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_client_is_active_client_last_login_client_password'),
        ('projects', '0016_procurement_client_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects_cp', to='crm.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_access_grants', to='projects.project')),
            ],
            options={
                'verbose_name': 'Client Project Access',
                'verbose_name_plural': 'Client Project Access',
                'unique_together': {('client', 'project')},
            },
        ),
    ]
