# Generated by Django 5.2.7 on 2025-12-16 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0001_initial'),
        ('crm', '0006_client_is_active_client_last_login_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproject',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_portal_projects', to='crm.client'),
        ),
    ]
