from django.urls import path
from .google_auth import google_auth_start, google_auth_callback, google_oauth_debug
from .views import (
    RegisterView, CustomTokenObtainPairView, CustomTokenRefreshView, LogoutView,
    SendInvitationView, StudioCreateView, StudioUpdateView, get_studio_users,
    get_current_user, AcceptInvitationView, PendingInvitationsView,
    update_current_user, get_currency_details, DashboardView,
    get_integration_status, StudioMemberManagementView, DailyBriefView,
    ForgotPasswordView, ResetPasswordView, ValidateResetTokenView, update_pay_per_hour,
    OtpSessionView, VerifyOtpView, ResendOtpView,
    # Settings screens
    studio_branding, studio_roles,
    studio_phase_templates, studio_phase_template_detail, studio_default_tasks,
    change_password, notification_preferences, appearance_preferences,
    get_default_studio_phases,
    project_templates, project_template_detail,
    project_template_phases, project_template_phase_detail,
    project_template_phase_tasks, project_template_phase_task_detail,
)

urlpatterns = [
    path('google/debug/', google_oauth_debug, name='google-oauth-debug'),
    path('google/login/', google_auth_start, name='google-auth-start'),
    path('google/callback/', google_auth_callback, name='google-auth-callback'),
    path('register/', RegisterView.as_view(), name='register'),
    path('otp-session/', OtpSessionView.as_view(), name='otp-session'),
    path('verify-otp/', VerifyOtpView.as_view(), name='verify-otp'),
    path('resend-otp/', ResendOtpView.as_view(), name='resend-otp'),
    path('login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('invite/', SendInvitationView.as_view(), name='send_invitation'),
    path('accept-invitation/', AcceptInvitationView.as_view(), name='accept_invitation'),
    path('studios/', StudioCreateView.as_view(), name='create_studio'),
    path('studios/update/', StudioUpdateView.as_view(), name='update_studio'),
    path('studio/members/', StudioMemberManagementView.as_view(), name='studio-members'),
    path('studio-users/', get_studio_users, name='studio-users'),
    path('self/', get_current_user, name='current-user'),
    path('self/update/', update_current_user, name='update-loggedin-user'),
    path('self/change-password/', change_password, name='change-password'),
    path('self/notification-preferences/', notification_preferences, name='notification-preferences'),
    path('self/appearance/', appearance_preferences, name='appearance-preferences'),
    path('pending-invites/', PendingInvitationsView.as_view(), name='pending-invites'),
    path('get-currency-details/', get_currency_details, name='get-currency-details'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('daily-brief/', DailyBriefView.as_view(), name='daily-brief'),
    path('integration-status/', get_integration_status, name='integration-status'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('validate-reset-token/', ValidateResetTokenView.as_view(), name='validate-reset-token'),
    path('update-pay-per-hour/', update_pay_per_hour, name='update-pay-per-hour'),
    # Studio settings
    path('studio/branding/', studio_branding, name='studio-branding'),
    path('studio/roles/', studio_roles, name='studio-roles'),
    path('studio/phase-templates/', studio_phase_templates, name='studio-phase-templates'),
    path('studio/phase-templates/<int:template_id>/', studio_phase_template_detail, name='studio-phase-template-detail'),
    path('studio/phase-templates/<int:template_id>/tasks/', studio_default_tasks, name='studio-default-tasks'),
    path('studio/default-phases/', get_default_studio_phases, name='studio-default-phases'),
    # Project templates (top-level templates with nested phases + tasks)
    path('studio/templates/', project_templates, name='project-templates'),
    path('studio/templates/<int:template_id>/', project_template_detail, name='project-template-detail'),
    path('studio/templates/<int:template_id>/phases/', project_template_phases, name='project-template-phases'),
    path('studio/templates/<int:template_id>/phases/<int:phase_id>/', project_template_phase_detail, name='project-template-phase-detail'),
    path('studio/templates/<int:template_id>/phases/<int:phase_id>/tasks/', project_template_phase_tasks, name='project-template-phase-tasks'),
    path('studio/templates/<int:template_id>/phases/<int:phase_id>/tasks/<int:task_id>/', project_template_phase_task_detail, name='project-template-phase-task-detail'),
]
