# Generated by Django 5.2.7 on 2026-05-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosubscription',
            name='plan_tier',
            field=models.CharField(blank=True, choices=[('beta', 'Beta Access'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=32, null=True),
        ),
    ]
