# Generated by Django 5.2.7 on 2025-12-11 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_client_created_by_alter_client_studio_and_more'),
        ('users', '0011_studio_gmail_studio_xero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=999, null=True)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('thread_id', models.CharField(max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='crm.client')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='users.studio')),
            ],
        ),
        migrations.CreateModel(
            name='GmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('token_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_token', to='users.studio')),
            ],
        ),
    ]
