# Generated by Django 5.2.7 on 2025-12-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_email_gmailtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmailtoken',
            name='studio',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='GmailToken',
        ),
    ]
