# Generated by Django 5.2.7 on 2026-01-28 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_client_created_at_alter_client_updated_at'),
        ('users', '0013_user_pay_per_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('referred_by', models.CharField(blank=True, max_length=255)),
                ('stage', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=50)),
                ('stage_updated_at', models.DateTimeField(auto_now=True)),
                ('lead_type', models.CharField(blank=True, max_length=50)),
                ('project_type', models.CharField(blank=True, max_length=100)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('property_size', models.PositiveIntegerField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50)),
                ('decision_maker_confirmed', models.BooleanField(default=False)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proposal_type', models.CharField(blank=True, max_length=100)),
                ('proposal_sent_date', models.DateField(blank=True, null=True)),
                ('negotiation_reason', models.CharField(blank=True, max_length=255)),
                ('revised_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_received', models.BooleanField(default=False)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('loss_reason', models.CharField(blank=True, max_length=255)),
                ('probability', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studio')),
            ],
        ),
    ]
