# Generated by Django 5.2.7 on 2026-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='project_created',
            field=models.BooleanField(default=False),
        ),
    ]
