# Generated by Django 5.2.7 on 2026-03-06 09:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_add_project_created_to_lead'),
        ('users', '0013_user_pay_per_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('cover_message', models.TextField(blank=True)),
                ('scope_description', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('terms_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_schedule', models.CharField(choices=[('50_50', '50/50 Split'), ('30_40_30', '30/40/30'), ('25_25_25_25', '25/25/25/25'), ('custom', 'Custom')], default='50_50', max_length=20)),
                ('status', models.CharField(choices=[('DFT', 'Draft'), ('SNT', 'Sent'), ('ACC', 'Accepted'), ('DCL', 'Declined')], default='DFT', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
                ('studio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studio')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='crm.proposal')),
            ],
        ),
    ]
