# Generated by Django 5.2.7 on 2026-03-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_clientnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='notes',
        ),
    ]
