# Generated by Django 5.2.7 on 2026-04-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_client_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='supplier_password',
            field=models.CharField(blank=True, help_text='Password for the supplier trade portal (Suppliers only)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='supplier_user_id',
            field=models.CharField(blank=True, help_text='User ID for the supplier trade portal (Suppliers only)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='trade_login_url',
            field=models.URLField(blank=True, help_text='Trade portal login URL (Suppliers only)', max_length=500, null=True),
        ),
    ]
