# Generated by Django 5.2.7 on 2026-04-08 05:26

from django.db import migrations, models


def copy_address_to_address_line_1(apps, schema_editor):
    Client = apps.get_model('crm', 'Client')
    Client.objects.exclude(address__isnull=True).exclude(address='').update(
        address_line_1=models.F('address')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_add_supplier_trade_fields'),
    ]

    operations = [
        # Add new fields first so the data migration can populate them
        migrations.AddField(
            model_name='client',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='additional_contacts',
            field=models.JSONField(blank=True, default=list),
        ),
        # Copy existing address data into address_line_1
        migrations.RunPython(copy_address_to_address_line_1, migrations.RunPython.noop),
        # Now safe to drop the old field
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
