# Generated by Django 5.2.7 on 2026-05-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_center', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='helparticlefeedback',
            new_name='help_center_categor_995947_idx',
            old_name='help_center_categor_6a8f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='helparticlefeedback',
            new_name='help_center_created_d43824_idx',
            old_name='help_center_created_8e2b41_idx',
        ),
    ]
