# Generated by Django 5.2.7 on 2025-11-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='stuio',
            new_name='studio',
        ),
        migrations.RemoveField(
            model_name='task',
            name='archive',
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('ARC', 'Archive')], default='AC', max_length=200, null=True),
        ),
    ]
