# Generated by Django 5.2.7 on 2025-11-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_stuio_task_studio_remove_task_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
