# Generated by Django 5.2.7 on 2025-11-25 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
        ('task', '0003_subtask_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comment.comments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtask',
            field=models.ManyToManyField(blank=True, to='task.subtask'),
        ),
    ]
