# Generated by Django 5.2.7 on 2025-11-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_subtask_created_at_subtask_created_by_subtask_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
