# Generated by Django 5.2.7 on 2026-03-24 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_created_at_alter_task_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
