# Generated by Django 5.2.7 on 2026-02-20 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0008_lead'),
        ('projects', '0020_phase_hour_budget_phase_total_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_portal_projects', to='crm.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_access_grants', to='projects.project')),
            ],
            options={
                'verbose_name': 'Contractor Project Access',
                'verbose_name_plural': 'Contractor Project Access',
                'unique_together': {('contractor', 'project')},
            },
        ),
    ]
