# Generated by Django 5.2.7 on 2026-02-20 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_portal', '0001_initial'),
        ('crm', '0008_lead'),
        ('documents', '0004_document_client_access'),
        ('projects', '0020_phase_hour_budget_phase_total_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorSharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='crm.client')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_shares', to='documents.document')),
            ],
            options={
                'verbose_name': 'Contractor Shared Document',
                'verbose_name_plural': 'Contractor Shared Documents',
                'unique_together': {('contractor', 'document')},
            },
        ),
        migrations.CreateModel(
            name='ContractorSharedProcurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_procurements', to='crm.client')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_shares', to='projects.procurement')),
            ],
            options={
                'verbose_name': 'Contractor Shared Procurement',
                'verbose_name_plural': 'Contractor Shared Procurements',
                'unique_together': {('contractor', 'procurement')},
            },
        ),
    ]
