# Generated by Django 5.2.7 on 2026-03-31 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_portal', '0002_contractorshareddocument_contractorsharedprocurement'),
        ('crm', '0014_remove_client_notes'),
        ('projects', '0024_procurement_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sender_type', models.CharField(choices=[('studio', 'Studio'), ('contractor', 'Contractor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_messages', to='crm.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_messages', to='projects.project')),
            ],
            options={
                'verbose_name': 'Contractor Message',
                'verbose_name_plural': 'Contractor Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
