# Generated by Django 5.2.7 on 2026-03-31 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_portal', '0003_contractormessage'),
        ('crm', '0014_remove_client_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('trade', models.CharField(blank=True, max_length=200, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='contractor_insurance/')),
                ('trade_cert', models.FileField(blank=True, null=True, upload_to='contractor_trade_certs/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to='crm.client')),
            ],
            options={
                'verbose_name': 'Contractor Profile',
                'verbose_name_plural': 'Contractor Profiles',
            },
        ),
    ]
