# Generated by Django 5.2.7 on 2025-12-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_invoice_created_at_invoice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='xero_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='xero_sync',
            field=models.BooleanField(default=False),
        ),
    ]
