# Generated by Django 5.2.7 on 2025-12-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_invoice_xero_sync_purchaseorder_xero_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='xero_id',
            field=models.CharField(blank=True, help_text='Xero invoice ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xero_invoice_number',
            field=models.CharField(blank=True, help_text='Xero-generated invoice number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xero_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync fails', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='xero_sync_status',
            field=models.CharField(blank=True, help_text='Sync status: pending, synced, failed', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='account_code',
            field=models.CharField(default='200', help_text='Xero account code', max_length=50),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='account_code',
            field=models.CharField(default='200', help_text='Xero account code', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='xero_id',
            field=models.CharField(blank=True, help_text='Xero bill ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='xero_invoice_number',
            field=models.CharField(blank=True, help_text='Xero-generated invoice number', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='xero_sync_error',
            field=models.TextField(blank=True, help_text='Error message if sync fails', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='xero_sync_status',
            field=models.CharField(blank=True, help_text='Sync status: pending, synced, failed', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='xero_sync',
            field=models.BooleanField(default=False, help_text='Enable sync with Xero'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='xero_sync',
            field=models.BooleanField(default=False, help_text='Enable sync with Xero'),
        ),
    ]
