# Generated by Django 5.2.7 on 2025-12-08 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_invoice_xero_id_invoice_xero_invoice_number_and_more'),
        ('library', '0005_product_is_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.product'),
        ),
        migrations.AddField(
            model_name='polineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.product'),
        ),
    ]
