# Generated by Django 5.2.7 on 2025-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_invoice_created_by_alter_invoice_studio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='xero_sync',
            field=models.BooleanField(default=True, help_text='Enable sync with Xero'),
        ),
    ]
