# Generated by Django 5.2.7 on 2025-12-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_purchaseorder_xero_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='xero_sync',
            field=models.BooleanField(default=True, help_text='Enable sync with Xero'),
        ),
    ]
