# Generated by Django 5.2.7 on 2025-12-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_invoice_xero_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_charge',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ffne',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
