# Generated by Django 5.2.7 on 2025-12-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_invoice_delivery_charge_invoice_ffne'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ffne_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
