# Generated by Django 5.2.7 on 2025-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoice_ffne_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='ffne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
