# Generated by Django 5.2.7 on 2025-12-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_invoice_ffne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
    ]
