# Generated by Django 5.2.7 on 2026-01-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_invoice_created_at_alter_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_charge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
