# Generated by Django 5.2.7 on 2026-03-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_purchaseorder_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='trade_invoice',
            field=models.FileField(blank=True, help_text='Supplier trade invoice PDF', null=True, upload_to='trade_invoices/'),
        ),
    ]
