# Generated by Django 5.2.7 on 2026-04-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_purchaseorder_trade_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='finance.purchaseorder'),
        ),
    ]
