from rest_framework import serializers

class ProductClipperRequestSerializer(serializers.Serializer):
    content = serializers.CharField(required=True, help_text="The raw content of the product page (HTML or text).")
    image_urls = serializers.ListField(child=serializers.URLField(), required=False, default=list, help_text="A list of image URLs found on the page.")

class SupplierSerializer(serializers.Serializer):
    id = serializers.IntegerField()
    name = serializers.CharField()
    company_name = serializers.CharField(required=False, allow_null=True)

class ProductClipperResponseSerializer(serializers.Serializer):
    name = serializers.CharField(required=False, allow_null=True)
    supplier = SupplierSerializer(required=False, allow_null=True)
    description = serializers.CharField(required=False, allow_null=True)
    currency = serializers.CharField(required=False, allow_null=True)
    trade_price = serializers.FloatField(required=False, allow_null=True)
    regular_price = serializers.FloatField(required=False, allow_null=True)
    materials = serializers.CharField(required=False, allow_null=True)
    dimension = serializers.CharField(required=False, allow_null=True)
    weight = serializers.CharField(required=False, allow_null=True)
    box_dimension = serializers.CharField(required=False, allow_null=True)
    assembly_required = serializers.BooleanField(required=False, allow_null=True)
    seat_width = serializers.CharField(required=False, allow_null=True)
    seat_depth = serializers.CharField(required=False, allow_null=True)
    seat_height = serializers.CharField(required=False, allow_null=True)
    composition = serializers.CharField(required=False, allow_null=True)
    construction = serializers.CharField(required=False, allow_null=True)
    feet = serializers.FloatField(required=False, allow_null=True)
    filling = serializers.CharField(required=False, allow_null=True)
    removeable_cushion = serializers.BooleanField(required=False, allow_null=True)
    removeable_legs = serializers.BooleanField(required=False, allow_null=True)
    frame = serializers.CharField(required=False, allow_null=True)
    type = serializers.CharField(required=False, allow_null=True)
    images = serializers.ListField(child=serializers.URLField(), required=False, allow_empty=True)

class ProductSaveSerializer(serializers.Serializer):
    name = serializers.CharField(required=True)
    description = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    currency = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    trade_price = serializers.FloatField(required=False, allow_null=True)
    regular_price = serializers.FloatField(required=False, allow_null=True)
    measurement = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    is_fav = serializers.BooleanField(required=False, default=False)
    materials = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    dimension = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    weight = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    box_dimension = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    assembly_required = serializers.BooleanField(required=False, default=False)
    seat_width = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    seat_depth = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    seat_height = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    composition = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    construction = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    feet = serializers.FloatField(required=False, allow_null=True)
    filling = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    removeable_cushion = serializers.BooleanField(required=False, default=True)
    removeable_legs = serializers.BooleanField(required=False, default=False)
    frame = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    type = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    instruction = serializers.CharField(required=False, allow_null=True, allow_blank=True)
    supplier_id = serializers.IntegerField(required=False, allow_null=True)
    image_urls = serializers.ListField(child=serializers.URLField(), required=False, default=list)
    url = serializers.URLField(required=False, allow_null=True)
