# Generated by Django 5.2.7 on 2025-11-25 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
        ('users', '0005_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='is_billable',
        ),
        migrations.AddField(
            model_name='timelog',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='users.studio'),
        ),
    ]
