# Generated by Django 5.2.7 on 2025-11-26 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_phase_created_at_phase_created_by_phase_studio_and_more'),
        ('task', '0005_subtask_created_at_subtask_created_by_subtask_studio_and_more'),
        ('time_tracker', '0002_remove_timelog_is_billable_timelog_studio'),
        ('users', '0005_invitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelog',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_logs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studio'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.task'),
        ),
    ]
