# Generated by Django 5.2.7 on 2025-11-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0003_timelog_created_at_timelog_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='clock_status',
            field=models.CharField(blank=True, choices=[('ON', 'on'), ('OFF', 'off')], max_length=200, null=True),
        ),
    ]
