# Generated by Django 5.2.7 on 2025-11-29 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0004_timelog_clock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='start_time',
        ),
        migrations.CreateModel(
            name='TimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='time_tracker.timelog')),
            ],
        ),
    ]
