# Generated by Django 5.2.7 on 2025-12-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0005_remove_timelog_end_time_remove_timelog_start_time_and_more'),
        ('users', '0009_alter_invitation_sender_alter_user_studio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.studio'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timesession',
            name='time_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_tracker.timelog'),
        ),
    ]
