# Generated by Django 5.2.7 on 2026-06-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
        ('time_tracker', '0007_alter_timelog_created_at_alter_timelog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='presentations.presentation'),
        ),
    ]
