# Generated by Django 5.2.7 on 2026-05-19 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0025_studio_notion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('workspace_id', models.CharField(blank=True, default='', max_length=64)),
                ('workspace_name', models.CharField(blank=True, default='', max_length=255)),
                ('bot_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notion_tokens_created', to=settings.AUTH_USER_MODEL)),
                ('studio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_token', to='users.studio')),
            ],
        ),
    ]
