# Generated by Django 5.2.7 on 2026-05-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
        ('projects', '0029_project_access_token'),
        ('users', '0025_studio_notion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionProjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_id', models.CharField(max_length=64)),
                ('database_title', models.CharField(blank=True, default='', max_length=255)),
                ('title_property', models.CharField(default='Name', help_text='Notion title property for project name', max_length=120)),
                ('status_property', models.CharField(blank=True, default='', help_text='Optional status/select property', max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notion_project_mapping', to='users.studio')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notion_mappings_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotionProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notion_page_id', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notion_links', to='projects.project')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notion_project_links', to='users.studio')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('studio', 'notion_page_id'), name='unique_notion_page_per_studio')],
            },
        ),
    ]
