"""
Django settings for techstyles project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def _env(key: str, default: str = '') -> str:
    """Read from environment; secrets must be set in server/.env (no defaults in code)."""
    return os.getenv(key, default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = _env('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError('SECRET_KEY is required. Set it in server/.env (see .env.example).')

DEBUG = _env('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in _env('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]

XERO_CLIENT_ID = _env('XERO_CLIENT_ID')
XERO_CLIENT_SECRET = _env('XERO_CLIENT_SECRET')
XERO_SCOPE = _env(
    'XERO_SCOPE',
    'offline_access accounting.transactions accounting.contacts',
)
XERO_REDIRECT_URI = _env('XERO_REDIRECT_URI', 'http://localhost:8000/xero/xero/callback/')

OPENAI_API_KEY = _env('OPENAI_API_KEY')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    "drf_spectacular",
    'crm',
    'finance',
    'library',
    'projects',
    'reports',
    'task',
    'time_tracker',
    'users',
    'attachment',
    'comment',
    'xero',
    'documents',
    'storages',
    'clipper',
    'gmail',
    'client_portal',
    'contractor_portal',
    'meetings',
    'notifications',
    'changelog',
    'billing',
    'integrations',
    'notion',
    'collaboration',
]

# Notion OAuth (https://www.notion.so/my-integrations)
NOTION_CLIENT_ID = _env('NOTION_CLIENT_ID')
NOTION_CLIENT_SECRET = _env('NOTION_CLIENT_SECRET')
NOTION_REDIRECT_URI = _env('NOTION_REDIRECT_URI', 'http://localhost:8000/notion/callback/')
NOTION_API_VERSION = _env('NOTION_API_VERSION', '2022-06-28')

VEXA_API_KEY = _env('VEXA_API_KEY')
VEXA_API_BASE = _env('VEXA_API_BASE', 'https://gateway.vexa.ai')

# AWS S3 Settings
AWS_ACCESS_KEY_ID = _env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = _env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = _env('AWS_STORAGE_BUCKET_NAME', 'techstyles')
AWS_S3_REGION_NAME = _env('AWS_S3_REGION_NAME', 'eu-west-2')
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None
STORAGES = {
    "default": {
        "BACKEND": "techstyles.storage_backends.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "techstyles.storage_backends.StaticStorage",
    },
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techstyles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'techstyles.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# S3 URLs for static and media files
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# Keep these for local development fallback if needed
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'techstyles.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

AUTH_USER_MODEL = 'users.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Focuspilot Backend API',
    'DESCRIPTION': 'API documentation for Focuspilot project management system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
}

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in _env(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000',
    ).split(',')
    if o.strip()
]
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# Required for cross-origin POST from https://focuspilot.io → https://api.focuspilot.io
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Auth cookies (login/register) — e.g. .focuspilot.io for api + www + app subdomains
AUTH_COOKIE_DOMAIN = _env('AUTH_COOKIE_DOMAIN')

# Behind Nginx TLS termination
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

GMAIL_CLIENT_ID = _env('GMAIL_CLIENT_ID')
GMAIL_CLIENT_SECRET = _env('GMAIL_CLIENT_SECRET')
GMAIL_REDIRECT_URI = _env('GMAIL_REDIRECT_URI', 'http://localhost:8000/gmail/callback')
GMAIL_SCOPES = _env(
    'GMAIL_SCOPES',
    'https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/calendar',
)

# Google Sign-In (studio accounts) — can reuse GMAIL_* credentials with a separate redirect URI
GOOGLE_AUTH_CLIENT_ID = _env('GOOGLE_AUTH_CLIENT_ID') or GMAIL_CLIENT_ID
GOOGLE_AUTH_CLIENT_SECRET = _env('GOOGLE_AUTH_CLIENT_SECRET') or GMAIL_CLIENT_SECRET
GOOGLE_AUTH_REDIRECT_URI = _env(
    'GOOGLE_AUTH_REDIRECT_URI',
    'http://localhost:8000/user/google/callback/',
)
GOOGLE_AUTH_SCOPES = _env('GOOGLE_AUTH_SCOPES', 'openid email profile')

RESEND_API_KEY = _env('RESEND_API_KEY')

FRONTEND_URL = _env('FRONTEND_URL', 'http://localhost:3000')
MARKETING_URL = _env('MARKETING_URL', 'http://localhost:3005')

# Absolute URL for email <img> (defaults to FRONTEND_URL/brand/email_logo.png)
EMAIL_LOGO_URL = _env('EMAIL_LOGO_URL')

# Stripe (SaaS subscriptions)
STRIPE_SECRET_KEY = _env('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = _env('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = _env('STRIPE_WEBHOOK_SECRET')
STRIPE_PRICE_STARTER = _env('STRIPE_PRICE_STARTER')
STRIPE_PRICE_PROFESSIONAL = _env('STRIPE_PRICE_PROFESSIONAL')
STRIPE_PRICE_ENTERPRISE = _env('STRIPE_PRICE_ENTERPRISE')
STRIPE_TRIAL_DAYS = int(_env('STRIPE_TRIAL_DAYS', '14'))
CLIENT_PORTAL_URL = _env('CLIENT_PORTAL_URL', 'http://localhost:3001')
CONTRACTOR_PORTAL_URL = _env('CONTRACTOR_PORTAL_URL', 'http://localhost:3002')
EMAIL_BACKEND = "techstyles.email_backend.CertifiEmailBackend"
EMAIL_HOST = _env('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(_env('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = _env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = _env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = _env('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@example.com')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File Upload Limits (50MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
