"""
Django settings for techstyles project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7)kclv1h=rxp*$2$m$hj3ad$tm(t*2==9ca-*))-f9=2y5u2zf')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

XERO_CLIENT_ID = os.getenv('XERO_CLIENT_ID', "ACC37794023848ED952F60A40C937E6A")
XERO_CLIENT_SECRET = os.getenv('XERO_CLIENT_SECRET', "RXPM2Odz8c7KKSRXunALNR8q037gzMgjgFWg8XJM1Bb3sNN7")
XERO_SCOPE = os.getenv('XERO_SCOPE', "offline_access accounting.transactions accounting.contacts")
XERO_REDIRECT_URI= os.getenv('XERO_REDIRECT_URI', "http://localhost:8000/xero/xero/callback/")

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', "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")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    "drf_spectacular",
    'crm',
    'finance',
    'library',
    'projects',
    'reports',
    'task',
    'time_tracker',
    'users',
    'attachment',
    'comment',
    'xero',
    'documents',
    'storages',
    'clipper',
    'gmail',
    'client_portal',
    'contractor_portal',
    'meetings',
    'notifications',
    'changelog',
]

VEXA_API_KEY = os.getenv('VEXA_API_KEY', '')
VEXA_API_BASE = os.getenv('VEXA_API_BASE', 'https://gateway.vexa.ai')

# AWS S3 Settings
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', 'AKIARSU7LCZG57ZHW757')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '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')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', 'techstyles')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'eu-west-2')
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = False
AWS_DEFAULT_ACL = None
STORAGES = {
    "default": {
        "BACKEND": "techstyles.storage_backends.MediaStorage",
    },
    "staticfiles": {
        "BACKEND": "techstyles.storage_backends.StaticStorage",
    },
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techstyles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'techstyles.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# S3 URLs for static and media files
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

# Keep these for local development fallback if needed
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'techstyles.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

AUTH_USER_MODEL = 'users.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'TechStyles Backend API',
    'DESCRIPTION': 'API documentation for TechStyles project management system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
}

_ALLOWED_ORIGINS_DEFAULT = 'https://app-stg.techstyles.ai,http://localhost:3000'
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', _ALLOWED_ORIGINS_DEFAULT).split(',')
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

GMAIL_CLIENT_ID = os.getenv('GMAIL_CLIENT_ID', "678827139040-i6gk4o0k3sfclaerbj9duarv0v12fl5k.apps.googleusercontent.com")
GMAIL_CLIENT_SECRET = os.getenv('GMAIL_CLIENT_SECRET', "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")
GMAIL_REDIRECT_URI = os.getenv('GMAIL_REDIRECT_URI', "http://127.0.0.1:8000/gmail/callback")
GMAIL_SCOPES = os.getenv('GMAIL_SCOPES', "https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/calendar")

RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:3000')
CLIENT_PORTAL_URL = os.getenv('CLIENT_PORTAL_URL', 'http://localhost:3001')
CONTRACTOR_PORTAL_URL = os.getenv('CONTRACTOR_PORTAL_URL', 'http://localhost:3002')
EMAIL_BACKEND = "techstyles.email_backend.CertifiEmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', "no-reply@techstyles.ai")
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', "jgzsatgoaeasbpjf")
DEFAULT_FROM_EMAIL = "no-reply@techstyles.ai"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# File Upload Limits (50MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
