# Generated by Django 5.2.7 on 2025-11-29 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('users', '0008_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studio'),
        ),
    ]
