# Generated by Django 5.2.7 on 2025-12-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_created_by_alter_document_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
