# Generated by Django 5.2.7 on 2026-02-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_client_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contractor_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
